debug: false
rollingUpdates: true
healthChecks: true
domain: "anubis.osiris.services"
vpnOnly: false
imagePullPolicy: "Always"

api:
  replicas: 3
  workers: 4

  healthCheck: true
  gunicorn_options: "--capture-output --enable-stdio-inheritance --preload --timeout 30"

  image: "registry.osiris.services/anubis/api"
  tag: "latest"

static:
  replicas: 3

  image: "registry.osiris.services/anubis/static"
  tag: "latest"
  healthCheck: true

reaper:
  enable: true
  schedule: "*/15 * * * *"

pipeline_api:
  replicas: 2
  workers: 2

  healthCheck: true

web:
  replicas: 2
  image: "registry.osiris.services/anubis/web"
  tag: "latest"

logstash:
  image: "registry.osiris.services/anubis/logstash"
  tag: "latest"

redis:
  image: "redis"
  tag: "4"

  resources:
    limits:
      memory: "1Gi"
    requests:
      memory: "1Gi"

rpc_workers:
  replicas: 10

theia:
  enable: true

  proxy:
    replicas: 3
    domain: "ide.anubis.osiris.services"
    image: "registry.osiris.services/anubis/theia-proxy"
    tag: "latest"
