apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: anubis
  name: pipeline-rpc
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: anubis-rpc-workers
  namespace: anubis

spec:
  selector:
    matchLabels:
      app: anubis-rpc-workers
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: anubis-rpc-workers
    spec:
      serviceAccountName: pipeline-rpc
      dnsPolicy: ClusterFirst
      containers:
      - name: anubis-rpc-worker
        image: registry.osiris.services/anubis/api:v2.0.0-alpha
        imagePullPolicy: IfNotPresent
        command:
        - "rq"
        - "worker"
        - "-u"
        - "redis://redis"
        env:
        # sqlalchemy uri
        - name: "DATABASE_URI"
          valueFrom:
            secretKeyRef:
              name: api
              key: database-uri
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-create-jobs
  namespace: anubis
  labels:
    rbac.authorization.k8s.io/pipeline-create-jobs: "true"
rules:
- apiGroups: ["batch", "extensions"]
  #
  # at the HTTP level, the name of the resource for accessing Job
  # objects is "jobs"
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pipeline-create-jobs
  namespace: anubis

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-create-jobs
subjects:
  - kind: ServiceAccount
    name: pipeline-rpc
    namespace: anubis
