
debug: false
rollingUpdates: true
healthChecks: true
domain: "anubis.osiris.services"
vpnOnly: false
imagePullPolicy: "Always"

api:
  replicas: 3
  workers: 4

  healthCheck: true
  gunicorn_options: "--capture-output --enable-stdio-inheritance --preload --timeout 30"

  image: "registry.osiris.services/anubis/api"
  tag: "v2.0.0"
  resources:
    requests:
      memory: "500Mi"


pipeline_api:
  replicas: 2
  workers: 2

  healthCheck: true

  resources:
    limits:
      memory: "500Mi"
    requests:
      memory: "500Mi"

web:
  replicas: 2
  image: "registry.osiris.services/anubis/web"
  tag: "v2.0.0"

logstash:
  image: "registry.osiris.services/anubis/logstash"
  tag: "latest"

elasticsearch:
  image: "elasticsearch"
  tag: "7.5.2"
  storage: "4Gi"
  storageClassName: "longhorn"
  initContainer: true

  resources:
    limits:
      memory: "2Gi"
    requests:
      memory: "2Gi"        

kibana:
  image: "kibana"
  tag: "7.5.2"


redis:
  image: "redis"
  tag: "4"

  resources:
    limits:
      memory: "1Gi"
    requests:
      memory: "1Gi"

rpc_workers:
  replicas: 2



