# Strip prefix /api
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - "/api"
---

# Strip prefix /api
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-ide
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - "/ide"
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress.route.anubis.api.public
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.debug }}
  entryPoints:
  - websecure
  {{- else }}
  entryPoints:
  - web
  {{- end }}
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`) && PathPrefix(`/api/`)
    middlewares:
    - name: strip-api
    services:
    - name: {{ include "chart.fullname" . }}-api
      port: 5000
  {{- if not .Values.debug }}
  tls:
    certResolver: le
  {{- end }}
---

# Public Ingress Route /*
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress.route.anubis.web
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    component: web
spec:
  {{- if .Values.debug }}
  entryPoints:
    - web
  {{- else }}
  entryPoints:
    - websecure
  {{- end }}
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`)
    services:
    - name: {{ include "chart.fullname" . }}-web
      port: 3000
  {{- if not .Values.debug }}
  tls:
    certResolver: le
  {{- end }}
---

# Public Ingress Route anubis.osiris.services/ide/
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress.route.theia.public
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    component: proxy
spec:
  {{- if .Values.debug }}
  entryPoints:
    - web
  {{- else }}
  entryPoints:
    - websecure
  {{- end }}
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`) && PathPrefix(`/ide/`)
    middlewares:
    - name: strip-ide
    services:
    - name: {{ include "chart.fullname" . }}-theia-proxy
      port: 5000
  - kind: Rule
    match: Host(`ide8000.{{ .Values.domain }}`)
    services:
    - name: {{ include "chart.fullname" . }}-theia-proxy
      port: 5000
  {{- if not .Values.debug }}
  tls:
    certResolver: le
  {{- end }}
---

# For the anubis-lms.io redirect when we deploy that
{{- if not .Values.debug }}
## Redirect with domain replacement
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: redirect-to-new
#  namespace: {{ .Release.Namespace }}
#  labels:
#    app.kubernetes.io/name: anubis
#    heritage: {{ .Release.Service | quote }}
#    release: {{ .Release.Name | quote }}
#spec:
#  redirectRegex:
#    regex: ^https://anubis.osiris.services/(.*)
#    replacement: https://anubis-lms.io/${1}
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: ingress.route.redirect.public
#  namespace: {{ .Release.Namespace }}
#  labels:
#    app.kubernetes.io/name: theia
#    component: proxy
#    heritage: {{ .Release.Service | quote }}
#    release: {{ .Release.Name | quote }}
#spec:
#  entryPoints:
#    - websecure
#  routes:
#  - kind: Rule
#    match: Host(`anubis.osiris.services`)
#    middlewares:
#    - name: redirect-to-new
#      namespace: {{ .Release.Namespace }}
#    services:
#    - name: {{ include "chart.fullname" . }}-web
#      port: 3000
#  tls:
#    certResolver: le
{{- end }}