debug: false
rollingUpdates: true
healthChecks: true
domain: "anubis.osiris.services"
vpnOnly: false
imagePullPolicy: "Always"
imagePullSecret: "anubis"

api:
  replicas: 2
  workers: 2
  datacenter: "mtc"
  gunicorn_options: "--capture-output --enable-stdio-inheritance --preload --timeout 30"
  image: "registry.digitalocean.com/anubis/api"
  tag: "latest"

reaper:
  enable: true
  schedule: "*/5 * * * *"
  suspend: false

visuals:
  enable: true
  schedule: "*/5 * * * *"
  suspend: false

pipeline_api:
  replicas: 1
  workers: 1

web:
  replicas: 2
  image: "registry.digitalocean.com/anubis/web"
  tag: "latest"

logstash:
  image: "registry.digitalocean.com/anubis/logstash"
  tag: "latest"

rpc:
  default:
    replicas: 3
  theia:
    replicas: 3    
  regrade:
    replicas: 3

theia:
  enable: true
  proxy:
    replicas: 2
    domain: "ide.anubis.osiris.services"
    image: "registry.digitalocean.com/anubis/theia-proxy"
    tag: "latest"

elasticsearch:
  service: elasticsearch-master.elastic.svc.cluster.local

backup:
  enable: true
  suspend: false
  schedule: "0 0 * * *"

  remote:
    enable: true
    secretName: anubis-backup-creds

